app_ambiente/apps/api_serve/urls.py
from django.conf.urls import patterns, include, url
from tastypie.api import Api
from .api import *
from .views import *

ambiente_api = Api(api_name = 'serve')
ambiente_api.register(LoginResource())
ambiente_api.register(SendSolicitudResource())
ambiente_api.register(TipoMaterialResource())
ambiente_api.register(FindBodegaResource())

urlpatterns = patterns('app_ambiente.apps.api_serve.views',
	url(r'^', include(ambiente_api.urls)),
)

app_ambiente/apps/principal/urls.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('app_ambiente.apps.principal.views',
	url(r'^$', login_required(TemplateView.as_view(template_name = 'home/index.html')), {'title': 'Bienvenido'}, name = 'home'),
)

app_ambiente/apps/solicitudes/urls.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('app_ambiente.apps.solicitudes.views',
	url(r'^make-solicitud/$', login_required(SolicitudView.as_view()), name = 'new_solicitud'),
	url(r'^find-bodega/$', 'find_bodega', name = 'find_bodega'),
	url(r'^save/$', 'save', name = 'save'),
	url(r'^solicitud-user/$', 'solicitud_user', name = 'solicitud_user'),
	url(r'^solicitud-bodega/$', 'view_solicitud', name = 'view_solicitud'),
)

app_ambiente/apps/users/urls.py
from .views import *
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import user_passes_test

login_forbidden = user_passes_test(lambda u: u.is_anonymous(), '/')

urlpatterns = patterns('app_ambiente.apps.users.views',
	#url(r'^registrate/$', login_forbidden(UserRegistrateView.as_view()), name = 'registrate'),
)

urlpatterns += [
	url(r'^login/$', login_forbidden(auth_views.login), {'template_name': 'users/login.html', 'extra_context': {'title': 'Ingreso'}}, name = 'login'),
	url(r'^logout/$', auth_views.logout, {'next_page': '/users/login'}, name = 'logout')
]

app_ambiente/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	url(r'^', include('app_ambiente.apps.principal.urls')),
	url(r'^users/', include('app_ambiente.apps.users.urls')),
	url(r'^solicitudes/', include('app_ambiente.apps.solicitudes.urls')),
	url(r'^api/', include('app_ambiente.apps.api_serve.urls')),
	url(r'^admin/', include(admin.site.urls)),
)

app_ambiente/apps/api_serve/models.py
from django.db import models

# Create your models here.

app_ambiente/apps/principal/models.py
from django.db import models

# Create your models here.

app_ambiente/apps/solicitudes/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class TipoMaterial(models.Model):
	nombre = models.CharField(max_length = 20)

	def __str__(self):
		return self.nombre

class Bodega(models.Model):
	nombre = models.CharField(max_length = 30)
	user = models.OneToOneField(User, null = True, blank = True)
	direccion = models.CharField(max_length = 40)

	def __str__(self):
		return self.nombre

class BodegaMaterial(models.Model):
	material = models.ForeignKey(TipoMaterial)
	precio = models.DecimalField(max_digits = 11, decimal_places = 2, blank = True, null = True)
	bodega = models.ForeignKey(Bodega)

	def __str__(self):
		return self.bodega.nombre

class SolicitudUser(models.Model):
	user = models.ForeignKey(User)
	bodega_material = models.ForeignKey(BodegaMaterial)
	peso_aprox = models.DecimalField(max_digits = 11, decimal_places = 2)
	fecha = models.DateField(default = datetime.now)

app_ambiente/apps/users/models.py
from django.contrib.auth.models import User
from django.db import models

class ProfileUser(models.Model):
	user = models.OneToOneField(User, primary_key = True)
	foto = models.ImageField(upload_to = 'img/users/', default = 'img/users/none.png', blank = True)
	numero_celular = models.CharField(max_length = 10, blank = True, null = True)
	direccion = models.CharField(max_length = 40, blank = True, null = True)
	key_user = models.CharField(max_length = 60, blank = True, null = True)

	def __str__(self):
		return str(self.user)

app_ambiente/apps/solicitudes/forms.py
# -*- encoding: utf-8 -*-
from django.forms import *
from django import forms
from .models import *

class SolicitudForm(forms.ModelForm):
	class Meta:
		model = SolicitudUser
		fields = '__all__'
		exclude = ('user',)
		labels = {
			'peso_aprox': 'Peso Aproximado (Kg)',
		}

	def __init__(self, *args, **kwargs):
		super(SolicitudForm, self).__init__(*args, **kwargs)
		self.fields['peso_aprox'].widget = widgets.TextInput(attrs = {'class': 'form-control', 'required': True})
		self.fields['bodega_material'] = forms.ModelChoiceField(label = 'Material', queryset = TipoMaterial.objects.all(), empty_label = 'Seleccione un Material', widget = forms.Select(attrs = {'class': 'form-control', 'required': True}))

class SolicitudUserForm(forms.ModelForm):
	class Meta:
		model = SolicitudUser
		fields = '__all__'

	def clean_user(self):
		print "Ole"

app_ambiente/apps/api_serve/views.py
from django.shortcuts import render

# Create your views here.

app_ambiente/apps/principal/views.py
from django.shortcuts import render

# Create your views here.

app_ambiente/apps/solicitudes/views.py
import json
from .forms import *
from .models import *
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.decorators import login_required

class SolicitudView(CreateView):
	model = SolicitudUser
	form_class = SolicitudForm
	template_name = 'solicitud/make_solicitud.html'

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(SolicitudView, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(SolicitudView, self).get_context_data(**kwargs)
		context['title'] = 'Solicitar'
		return context

def find_bodega(request):
	results = []
	response = {}
	for material in TipoMaterial.objects.get(pk = request.GET.get('material')).bodegamaterial_set.all():
		response['pk'] = material.pk
		response['bodega'] = material.bodega.nombre
		response['bodega_dir'] = material.bodega.direccion
		response['precio'] = str(int(material.precio))
		results.append(response)
		response = {}
	return HttpResponse(json.dumps(results), content_type = 'application/json')

def save(request):
	response = {}
	print request.GET.get('bodega_material')
	bodega_material = BodegaMaterial.objects.get(pk = request.GET.get('bodega_material'))
	peso_aprox = request.GET.get('peso_aprox')
	solicitud = SolicitudUser(user = request.user, bodega_material = bodega_material, peso_aprox = peso_aprox)
	solicitud.save()
	response['msg'] = 'Guardado con exito'
	return HttpResponse(json.dumps(response), content_type = 'application/json')

def solicitud_user(request):
	solicitud = SolicitudUser.objects.filter(user = request.user)
	return render(request, 'solicitud/solicitud_user.html', {'title': 'Lista de Solicitudes', 'solicitudes': solicitud})

def view_solicitud(request):
	solicitud = BodegaMaterial.objects.filter(bodega = request.user.bodega)
	return render(request, 'solicitud/solicitud_bodega.html', {'title': 'Lista de Solicitudes', 'solicitudes': solicitud})

app_ambiente/apps/users/views.py
from django.shortcuts import render

# Create your views here.

app_ambiente/apps/principal/templates/elements/nav.html
<nav class="navbar navbar-trans navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsible">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">APPAMBIENTE</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar-collapsible">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="{% url 'home' %}">Inicio</a></li>
        <li><a href="#section2">¿Quienes somos?</a></li>
        <li><a href="#section3">Contactenos</a></li>
        
        <li>&nbsp;</li>
      </ul>
      <form class="navbar-form">
        <div class="form-group" style="display:inline;">
          <div class="input-group"> 
            <div class="input-group-btn">
              <button type="button" class="btn btn-default " >Ingrese</button>
             
            </div>
            
          </div>
        </div>
      </form>
    </div>
  </div>
</nav>

app_ambiente/apps/principal/templates/home/index.html
{% extends 'layout/base.html' %}

{% block content %}
	{% include 'elements/nav.html' %}
	<section class="container-fluid" id="section1">
  	<h1 class=" v-center"><img src="D\app_ambiente\app_ambiente\logoapambiente2.png" class="img"></h1>
 	
  	<div class="container">
      <div class="row">
          <div class="col-sm-4">
            <div class="row">
              <div class="col-sm-10 col-sm-offset-2 text-center"><h3>¿Quienes somos?</h3><p>Somos una solucion para nuestro mundo...</p><i class="fa fa-cog fa-5x"></i></div>
            </div>
          </div>
          <div class="col-sm-4 text-center">
            <div class="row">
              <div class="col-sm-10 col-sm-offset-1 text-center"><h3>¿Que queremos?</h3><p>Demostrar que con nuestra basura podemos generar ingresos y diversas utilidades...</p><i class="fa fa-user fa-5x"></i></div>
            </div>
          </div>
          <div class="col-sm-4 text-center">
            <div class="row">
              <div class="col-sm-10 text-center"><h3>Contactanos</h3><p>Quieres ser parte de nuestra comunidad...registrate</p><i class="fa fa-mobile fa-5x"></i></div>
            </div>
          </div>
      </div><!--/row-->
    <div class="row"><br></div>
  </div><!--/container-->
</section>
{% endblock content %}

app_ambiente/apps/principal/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{{ title }}</title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/styles.css' %}">
		{% block content_css %}{% endblock content_css %}
	</head>
	<body>
		<div class="container text-center content-centered" style="margin-top:100px">
			{% block content %}{% endblock content %}
		
		
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script>
			{% block content_script %}{% endblock content_script %}
		</script>
	</body>
</html>

app_ambiente/apps/principal/templates/solicitud/make_solicitud.html
{% extends 'layout/base.html' %}

{% block content %}
	<form role="form" action="{% url 'new_solicitud' %}" method="POST">
		{% csrf_token %}
		<div class="form-group">
			<label>{{ form.peso_aprox.label }}</label>
			{{ form.peso_aprox }}
		</div>
		<div class="form-group">
			<label>{{ form.bodega_material.label }}</label>
			{{ form.bodega_material }}
		</div>
		<div class="row">
			<div id="price"></div>
		</div>
		<br>
		<div class="form-group">
			<button type="submit" class="btn btn-success">Hacer solicitud</button>
		</div>
	</form>
{% endblock content %}

{% block content_script %}
	var bodega_material = 0;
	var peso = $('#id_peso_aprox');
	$('#id_bodega_material').change(function(){
		$('#price').empty();
		if(peso.val() != ''){
			$.get("/solicitudes/find-bodega", {material: $(this).val()}, function(response){
				if(response != ''){
					$('#price').append('<h3>Bodegas disponibles</h3>');
					for(var data in response){
						$('#price').append(
							'<div class="col-xs-6">'+
								'<p><strong>Bodega: </strong>'+response[data].bodega+'</p>'+
								'<p><strong>Dirección: </strong>'+response[data].bodega_dir+'</p>'+
								'<p><strong>Precio aproximado a pagar: </strong>'+(peso.val() * response[data].precio)+'</p>'+
								'<a href="#" id="select" val="'+response[data].pk+'" class="btn btn-info">Seleccionar</a>'+
							'</div>'
						);
					}
				}else{
					$('#price').append('<h3>No hay bodegas disponibles</h3>');
					bodega_material = 0;
				}
			});
		}else{
			alert('Ingresa primero el peso aproximado');
			peso.focus();
		}
	});
	$('html').on('click', '#select', function(){
		bodega_material = $(this).attr('val');
		return false;
	});
	$("form").submit(function(){
		if(bodega_material == 0){
			alert('Debe seleccionar una bodega');
		}else{
			$.get("/solicitudes/save", {bodega_material: bodega_material, peso_aprox: peso.val()}, function(response){
				alert(response.msg);
				window.location.href = "{% url 'solicitud_user' %}"
			});
		}
		return false;
	});
{% endblock content_script %}

app_ambiente/apps/principal/templates/solicitud/solicitud_bodega.html
{% extends 'layout/base.html' %}

{% block content %}
	<h2>Lista de solicitudes</h2>
	<div class="row text-left">
		{% for solicitud in solicitudes %}
			<div class="col-sm-6">
				<h4>{{ solicitud.material }}</h4>
				<ul>
					{% for s_user in solicitud.solicituduser_set.all %}
						<li><strong>Fecha: </strong>{{ s_user.fecha }}</li>
						<ul>
							<li><strong>Usuario: </strong>{{ s_user.user.first_name }}</li>
							<li><strong>Peso: </strong>{{ s_user.peso_aprox }}</li>
						</ul>
					{% endfor %}
				</ul>
			</div>
		{% endfor %}
	</div>
{% endblock content %}

app_ambiente/apps/principal/templates/solicitud/solicitud_user.html
{% extends 'layout/base.html' %}

{% block content %}
	<h2>Mis solicitudes</h2>
	<div class="row text-left">
	{% for solicitud in solicitudes %}
		<div class="col-xs-6">
			<p><strong>Fecha: </strong>{{ solicitud.fecha }}</p>
			<p><strong>Material: </strong>{{ solicitud.bodega_material.material.nombre }}</p>
			<p><strong>Peso: </strong>{{ solicitud.peso_aprox }}</p>
			<p><strong>Bodega: </strong>{{ solicitud.bodega_material.bodega.nombre }}</p>
			<p><strong>Dirección bodega: </strong>{{ solicitud.bodega_material.bodega.direccion }}</p>
		</div>
	{% endfor %}
	<br>
	<div class="text-center">
		<a href="{% url 'new_solicitud' %}" class="btn btn-success" id="load-page">Nueva Solicitud</a>
	</div>
	</div>
{% endblock content %}

app_ambiente/apps/principal/templates/users/login.html
{% extends 'layout/base.html' %}

{% block content %}
	<div class="col-md-4 col-md-offset-4">
		{% if form.errors %}
			<div class="alert alert-danger text-center" role="alert">
				Usuario y/o contraseña incorrecta.
			</div>
		{% endif %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><strong>{{ title }} </strong></h3>
			</div>
			<div class="panel-body text-center">
				<form role="form" action="{% url 'login' %}" method="POST">
					{% csrf_token %}
						<input id="id_username" type="text" class="form-control" name="username" value="" placeholder="Usuario">
						<input id="id_password" type="password" class="form-control" name="password" placeholder="Contraseña">
					<button type="submit" class="btn btn-success">Ingresar</button>
					<hr style="margin-top:10px;margin-bottom:10px;">
				</form>
			</div>
		</div>
	</div>
{% endblock content %}